module.exports = {
  "tokens":{
    "YELP_CONSUMER_KEY": "YOUR_YELP_CONSUMER_KEY_HERE",
    "YELP_CONSUMER_SECRET": "YOUR_YELP_CONSUMER_SECRET_HERE",
    "YELP_TOKEN": "YOUR_YELP_TOKEN_HERE",
    "YELP_TOKEN_SECRET": "YOUR_YELP_TOKEN_SECRET_HERE"
  }
};